strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
    mac:
      imageName: 'macos-latest'
    windows:
      imageName: 'windows-latest'

pool:
  vmImage: $(imageName)

trigger:
  - develop

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '12.x'
    displayName: 'Install Node.js'

  - script: |
      yarn install
    displayName: 'Yarn install'

  - script: |
      yarn package
    displayName: 'Package Electron App'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: './release'
      includeRootFolder: false
      archiveType: 'tar'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).tar.gz'
    displayName: 'Package the service'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).tar.gz'
      ArtifactName: 'aye_player_build'
      publishLocation: 'Container'
    displayName: 'Publish the build artifact to storage'
