strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
    mac:
      imageName: 'macos-latest'
    windows:
      imageName: 'windows-latest'

pool:
  vmImage: $(imageName)

trigger:
  - develop

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '12.x'
    displayName: 'Install Node.js'

  - script: |
      yarn install
    displayName: 'Yarn install'

  - script: |
      yarn package
    displayName: 'Build'

  - task: DeleteFiles@1
    condition: eq($(imageName), 'linux-latest')
    inputs:
      SourceFolder: './release'
      Contents: 'linux-unpacked'
    displayName: 'Deleting unneeded linux files'

  - task: DeleteFiles@1
    condition: eq($(imageName), 'macos-latest')
    inputs:
      SourceFolder: './release'
      Contents: 'mac'
    displayName: 'Deleting unneeded mac files'

  - task: DeleteFiles@1
    condition: eq($(imageName), 'windows-latest')
    inputs:
      SourceFolder: './release'
      Contents: 'win-unpacked'
    displayName: 'Deleting unneeded windows files'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: './release'
      includeRootFolder: false
      archiveType: 'tar'
      archiveFile: '$(Build.ArtifactStagingDirectory)/AYE_Player_$(imageName).tar.gz'
      replaceExistingArchive: true
    displayName: 'Package'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/AYE_Player_$(imageName).tar.gz'
      ArtifactName: 'aye_player_build'
      publishLocation: 'Container'
    displayName: 'Publish to Artifact Storage'
