trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "12.x"
    displayName: "Install Node.js"

  - script: |
      sudo apt-get install dpkg fakeroot -y
    displayName: "Install dpkg & fakeroot"

  - script: |
      yarn install
    displayName: "Yarn install"
  
  - script: |
      yarn package
    displayName: "Package Electron App"

  - task: DeleteFiles@1
    inputs:
      SourceFolder: './release'
      Contents: 'linux-unpacked'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: './release'
      includeRootFolder: false
      archiveType: 'tar'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).tar.gz'
      replaceExistingArchive: true
    displayName: 'Package the service'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).tar.gz'
      ArtifactName: 'aye_player_build'
      publishLocation: 'Container'
    displayName: 'Publish the build artifact to storage'