name: Bump Homebrew Cask — aye-player
on:
  workflow_dispatch:                      # allow manual trigger
  release:
    types: [published]

jobs:
  bump-homebrew-cask:
    runs-on: macos-13

    steps:
    - name: Bump Homebrew Cask
      uses: eugenesvk/action-homebrew-bump-cask@3.8.4
      with:
        tap       	: AYE-Player/homebrew-tap	# [opt] |homebrew/core|
        cask      	: aye-player          	# [req] Cask name
        token     	: ${{secrets.BUMP_CASK_TOKEN}}	# [req] Custom GitHub access token with the 'public_repo'
        # org     	: ORG               	# [opt] Create tap repo fork in organization
        # tag     	: ${{github.ref}}   	# [opt] Determined automatically
        # revision	: ${{github.sha}}   	# [opt] Determined automatically
        # force   	: false             	# [opt] Don't check for already open PR
