name: Build/release

on:
  push:
    tags:
      - "v*"

jobs:
  build_and_release_artifacts:
    name: Build and Upload
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-13, windows-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node v20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build/release Electron app
        uses: aye-player/action-electron-builder@master
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}

      - name: Bump Cask
        uses: macauley/action-homebrew-bump-cask@v1
        with:
          # Required, custom GitHub access token with only the 'public_repo' scope enabled
          token: ${{secrets.BUMP_CASK_TOKEN}}
          # Bump all outdated casks in this tap
          tap: AYE-Player/homebrew-aye-player
          # Bump only these casks if outdated
          cask: aye-player-develop
          livecheck: true
          dryrun: true
